command: [
  "uvicorn",
  "server.app:app"
]

# Run as service principal for automatic authentication
# This eliminates the need for storing OAuth secrets - the app inherits the SP's identity
run_as:
  service_principal_name: nethra_austin

permissions:
  # Model serving endpoints
  - permission: CAN_QUERY
    object_type: serving-endpoints
    object_id: databricks-gpt-5-nano
  - permission: CAN_QUERY
    object_type: serving-endpoints
    object_id: databricks-gpt-5-mini
  - permission: CAN_QUERY
    object_type: serving-endpoints
    object_id: databricks-gpt-5-2
  # SQL warehouse for Unity Catalog queries
  - permission: CAN_USE
    object_type: sql-warehouses
    object_id: 4b9b953939869799

env:
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '2517718719552044'
  - name: 'DC_ASSISTANT_MODE'
    value: 'local'
  - name: 'LLM_MODEL'
    value: 'databricks-gpt-5-mini'
  - name: 'UC_CATALOG'
    value: 'ac_demo'
  - name: 'UC_SCHEMA'
    value: 'dc_assistant'
  - name: 'PROMPT_NAME'
    value: 'ac_demo.dc_assistant.dcassistant'
  - name: 'DC_ASSISTANT_CONFIG_JSON'
    value: >
      {
        "workspace": {
          "catalog": "ac_demo",
          "schema": "dc_assistant"
        },
        "data_collection": {
          "seasons": [2022, 2023, 2024]
        },
        "mlflow": {
          "experiment_id": "2517718719552044"
        },
        "prompt_registry": {
          "prompt_name": "ac_demo.dc_assistant.dcassistant",
          "reflection_model": "databricks:/databricks-gpt-5-2"
        },
        "llm": {
          "endpoint_name": "databricks-gpt-5-mini",
          "judge_model": "databricks:/databricks-gpt-5-2"
        },
        "model": {
          "model_name": "ac_dc_assistant",
          "uc_model_name": "ac_demo.dc_assistant.ac_dc_assistant"
        },
        "evaluation": {
          "dataset_name": "ac_demo.dc_assistant.dc_assistant_eval_trace_data",
          "label_schema_name": "football_analysis_base",
          "labeling_session_name": "dcassistant_eval_labeling",
          "assigned_users": ["austin.choi@databricks.com"]
        },
        "judges": {
          "aligned_judge_name": "football_analysis_judge_align"
        },
        "optimization": {
          "optimization_dataset_name": "ac_demo.dc_assistant.dcassistant_optimization_data"
        },
        "alignment": {
          "alignment_runs_table": "ac_demo.dc_assistant.alignment_runs"
        },
        "tools": {
          "uc_tool_names": [
            "ac_demo.dc_assistant.who_got_ball_by_down_distance",
            "ac_demo.dc_assistant.who_got_ball_by_offense_situation",
            "ac_demo.dc_assistant.tendencies_by_offense_formation",
            "ac_demo.dc_assistant.tendencies_by_down_distance",
            "ac_demo.dc_assistant.tendencies_by_drive_start",
            "ac_demo.dc_assistant.tendencies_by_score_2nd_half",
            "ac_demo.dc_assistant.tendencies_two_minute_drill",
            "ac_demo.dc_assistant.who_got_ball_by_down_distance_and_form",
            "ac_demo.dc_assistant.who_got_ball_two_minute_drill",
            "ac_demo.dc_assistant.first_play_after_turnover",
            "ac_demo.dc_assistant.screen_play_tendencies",
            "ac_demo.dc_assistant.success_by_pass_rush_and_coverage"
          ]
        },
        "prompt_registry_auth": {
          "use_service_principal": true,
          "service_principal_id": "5d5718d0-82bc-4a3f-980f-ae56b792a273",
          "databricks_host": "https://e2-demo-field-eng.cloud.databricks.com/"
        }
      }
