import React, { useRef, useState } from "react";
import { MarkdownContent } from "@/components/markdown-content";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Loader2,
  Send,
  ExternalLink,
  CheckCircle2,
  Wrench,
  Upload,
  ImageIcon,
  PlayCircle,
} from "lucide-react";

const formatToolName = (name: string) => {
  const parts = name.split("__");
  return parts.length > 2 ? parts.slice(2).join("__") : name;
};

interface ToolCall {
  tool: string;
  arguments: Record<string, any>;
  status: "pending" | "success" | "error";
}

interface FormationPreset {
  id: string;
  label: string;
  team: string;
  src: string;
  defaultQuestion: string;
}

// The question intentionally never names the team or personnel grouping --
// that information is only on the diagram (team name in the title, personnel
// count in the subtitle). The agent has to read the image before it knows
// which team/formation to query, instead of the image being decorative
// while the question text does all the work. Personnel counts on each
// diagram are chosen to match a REAL, common personnel_bucket returned by
// the tendencies_by_offense_formation UC tool for that team/season (see
// scratchpad diagrams/gen_formations_v2.py) so the agent's tool-derived
// numbers never contradict what's drawn.
const PRELOADED_IMAGES: FormationPreset[] = [
  {
    id: "shotgun-trips",
    label: "Shotgun, 1 RB / 1 TE / 3 WR, Trips Right",
    team: "Kansas City Chiefs (2024)",
    src: "/formation-shotgun-trips.png",
    defaultQuestion:
      "What coverage beats this look, based on this team's actual 2024 tendency data?",
  },
  {
    id: "under-center-12",
    label: "Under Center, 1 RB / 2 TE / 2 WR",
    team: "Detroit Lions (2024)",
    src: "/formation-under-center-12.png",
    defaultQuestion:
      "What's our best run fit against this look, based on this team's actual 2024 tendency data?",
  },
  {
    id: "shotgun-12-tight",
    label: "Shotgun, 1 RB / 2 TE / 2 WR, Tight Set",
    team: "Buffalo Bills (2024)",
    src: "/formation-shotgun-12-tight.png",
    defaultQuestion:
      "How should we defend this look, based on this team's actual 2024 tendency data?",
  },
  {
    id: "pistol-bunch-left",
    label: "Pistol, 1 RB / 1 TE / 3 WR, Bunch Left",
    team: "Philadelphia Eagles (2024)",
    src: "/formation-pistol-bunch-left.png",
    defaultQuestion:
      "What's our best call against this bunch look, based on this team's actual 2024 tendency data?",
  },
];

// A real trace generated by sending PRELOADED_IMAGES[0] to the agent — see
// mlflow_demo/agent/agent.py's predict_stream_local(image_content=...) for
// how the image is kept as a single-turn multimodal message, and
// app.yaml's MLFLOW_TRACE_EXTRACT_ATTACHMENTS=false for why the image
// renders inline in this workspace's trace UI (it only resolves raw base64
// data URIs today, not mlflow-attachment:// references). The question omits
// the team name on purpose -- the agent reads it off the diagram, then uses
// it to parameterize the tool calls, so the image is load-bearing rather
// than redundant with the question text.
const PREGENERATED_EXAMPLE = {
  ...PRELOADED_IMAGES[0],
  traceId: "trace:/main.austin_choi_demo.nfl_dc_assistant_trace/9b9ec76c9a90b8fc3783a27742485aa5",
};

const blobToBase64 = (blob: Blob): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve((reader.result as string).split(",")[1] || "");
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });

export function MultiModalDemo() {
  const [uploadedImage, setUploadedImage] = useState<{
    dataUrl: string;
    base64: string;
    mimeType: string;
  } | null>(null);
  const [question, setQuestion] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [loading, setLoading] = useState(false);
  const [runningPresetId, setRunningPresetId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamingContent, setStreamingContent] = useState("");
  const [toolCalls, setToolCalls] = useState<ToolCall[]>([]);
  const [currentTraceId, setCurrentTraceId] = useState<string | null>(null);
  const [traceUrlTemplate, setTraceUrlTemplate] = useState<string>("");

  React.useEffect(() => {
    fetch("/api/tracing_experiment")
      .then((res) => res.json())
      .then((data) => setTraceUrlTemplate(data.trace_url_template))
      .catch((err) => console.error("Failed to fetch experiment info:", err));
  }, []);

  const handleUpload = (file: File) => {
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = reader.result as string;
      const base64 = dataUrl.split(",")[1] || "";
      setUploadedImage({ dataUrl, base64, mimeType: file.type || "image/png" });
      if (!question) {
        setQuestion("What formation/coverage is this, and what should we call against it?");
      }
    };
    reader.readAsDataURL(file);
  };

  const runAnalysis = async (base64: string, mimeType: string, questionText: string) => {
    setLoading(true);
    setIsStreaming(true);
    setError(null);
    setStreamingContent("");
    setToolCalls([]);
    setCurrentTraceId(null);

    try {
      const response = await fetch("/api/dc-assistant/analyze-stream", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question: questionText,
          image_base64: base64,
          image_mime_type: mimeType,
        }),
      });

      if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);

      const reader = response.body?.getReader();
      const decoder = new TextDecoder();
      let accumulatedContent = "";
      if (!reader) throw new Error("No response body");

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value);
        for (const line of chunk.split("\n")) {
          if (!line.startsWith("data: ")) continue;
          try {
            const data = JSON.parse(line.slice(6));
            if (data.type === "token") {
              accumulatedContent += data.content;
              setStreamingContent(accumulatedContent);
            } else if (data.type === "tool_call") {
              accumulatedContent = "";
              setStreamingContent("");
              setToolCalls((prev) => [
                ...prev,
                {
                  tool: data.tool.name || data.tool.function_name || "Unknown",
                  arguments: data.tool.arguments ? JSON.parse(data.tool.arguments) : {},
                  status: "success",
                },
              ]);
            } else if (data.type === "done") {
              setCurrentTraceId(data.trace_id || null);
            } else if (data.type === "error") {
              setError(data.error);
            }
          } catch (e) {
            console.error("Failed to parse SSE data:", e);
          }
        }
      }
    } catch (err: any) {
      console.error("Error analyzing:", err);
      setError(err.message || "Failed to analyze");
    } finally {
      setLoading(false);
      setIsStreaming(false);
      setRunningPresetId(null);
    }
  };

  const handleRunPreset = async (preset: FormationPreset) => {
    if (loading) return;
    setUploadedImage(null);
    setQuestion(preset.defaultQuestion);
    setRunningPresetId(preset.id);

    try {
      const blob = await fetch(preset.src).then((r) => r.blob());
      const mimeType = blob.type || "image/png";
      const base64 = await blobToBase64(blob);
      await runAnalysis(base64, mimeType, preset.defaultQuestion);
    } catch (err: any) {
      setError(err.message || "Failed to load formation image");
      setRunningPresetId(null);
    }
  };

  const handleAskCustom = async () => {
    if (!uploadedImage || !question.trim()) {
      setError("Upload an image and enter a question");
      return;
    }
    await runAnalysis(uploadedImage.base64, uploadedImage.mimeType, question);
  };

  return (
    <div className="space-y-6">
      {/* Pre-generated example */}
      <Card className="border-blue-200 bg-blue-50/30 dark:border-blue-900 dark:bg-blue-950/20">
        <CardHeader>
          <CardTitle className="text-base">Pre-generated example</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-[200px_1fr] gap-4 items-start">
            <img
              src={PREGENERATED_EXAMPLE.src}
              alt={PREGENERATED_EXAMPLE.label}
              className="rounded-lg border w-full"
            />
            <div className="space-y-2">
              <p className="text-sm font-medium">{PREGENERATED_EXAMPLE.label}</p>
              <p className="text-sm text-muted-foreground italic">
                "{PREGENERATED_EXAMPLE.defaultQuestion}"
              </p>
              <p className="text-xs text-muted-foreground">
                Note the question never says which team this is — the agent read the team
                name and personnel grouping directly off the diagram, then used that to call
                the right Unity Catalog tools and return a grounded coverage recommendation —
                all in one traced session.
              </p>
              {traceUrlTemplate && (
                <Button
                  variant="default"
                  size="sm"
                  className="bg-blue-600 hover:bg-blue-700"
                  onClick={() =>
                    window.open(`${traceUrlTemplate}${PREGENERATED_EXAMPLE.traceId}`, "_blank")
                  }
                >
                  <ExternalLink className="h-4 w-4 mr-2" />
                  View this trace
                </Button>
              )}
              <p className="text-xs text-muted-foreground">
                Note: the image isn't shown on the trace's Summary tab -- click into{" "}
                <strong>Details &amp; Timeline → Completions</strong> to see it in the Chat view.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          {/* Try it live: one-click formation gallery */}
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Try it live — click a formation to run it</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                {PRELOADED_IMAGES.map((img) => {
                  const isRunningThis = runningPresetId === img.id && loading;
                  return (
                    <button
                      key={img.id}
                      onClick={() => handleRunPreset(img)}
                      disabled={loading}
                      className="group relative rounded-lg border-2 border-transparent overflow-hidden text-left transition-colors hover:border-primary disabled:cursor-not-allowed"
                    >
                      <img src={img.src} alt={img.label} className="w-full" />
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition-colors flex items-center justify-center">
                        {isRunningThis ? (
                          <Loader2 className="h-8 w-8 text-white animate-spin" />
                        ) : (
                          <PlayCircle className="h-8 w-8 text-white opacity-0 group-hover:opacity-100 transition-opacity" />
                        )}
                      </div>
                      <div className="p-2 bg-background">
                        <p className="text-xs font-medium">{img.label}</p>
                        <p className="text-xs text-muted-foreground">{img.team}</p>
                      </div>
                    </button>
                  );
                })}
              </div>
              <p className="text-xs text-muted-foreground">
                Each click sends that diagram + its question to the agent live and streams back
                a real, traced response.
              </p>
            </CardContent>
          </Card>

          {/* Write your own question */}
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Or write your own question</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                className="hidden"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) handleUpload(file);
                }}
              />
              <Button
                variant="outline"
                className="w-full"
                onClick={() => fileInputRef.current?.click()}
              >
                <Upload className="h-4 w-4 mr-2" />
                {uploadedImage ? "Change uploaded image" : "Upload your own diagram/photo"}
              </Button>

              {uploadedImage && (
                <img
                  src={uploadedImage.dataUrl}
                  alt="Uploaded"
                  className="rounded-lg border max-h-40 mx-auto"
                />
              )}

              <Label htmlFor="mm-question" className="font-semibold">
                Ask a question about it
              </Label>
              <Textarea
                id="mm-question"
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                placeholder="What coverage beats this look?"
                rows={3}
              />

              <Button
                onClick={handleAskCustom}
                disabled={loading || !uploadedImage}
                className="w-full"
              >
                {loading && !runningPresetId ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Asking DC Assistant...
                  </>
                ) : (
                  <>
                    <Send className="mr-2 h-4 w-4" />
                    Ask DC Assistant
                  </>
                )}
              </Button>
            </CardContent>
          </Card>

          {error && (
            <Alert variant="destructive">
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
        </div>

        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Generated Response</CardTitle>
            </CardHeader>
            <CardContent>
              {toolCalls.length > 0 && (
                <div className="mb-4">
                  <p className="text-xs font-semibold text-muted-foreground mb-2">
                    Tools used by DC Assistant:
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {toolCalls
                      .filter(
                        (call, idx, arr) =>
                          arr.findIndex((c) => formatToolName(c.tool) === formatToolName(call.tool)) === idx,
                      )
                      .map((call, idx) => (
                        <div
                          key={idx}
                          className="flex items-center gap-1.5 px-3 py-1.5 bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 rounded-full"
                        >
                          <Wrench className="h-3 w-3 text-amber-600 dark:text-amber-400 flex-shrink-0" />
                          <code className="text-xs font-medium text-amber-800 dark:text-amber-200">
                            {formatToolName(call.tool)}
                          </code>
                          <CheckCircle2 className="h-3 w-3 flex-shrink-0 text-green-600" />
                        </div>
                      ))}
                  </div>
                </div>
              )}

              {isStreaming && !streamingContent ? (
                <div className="flex flex-col items-center justify-center py-12 space-y-4">
                  <Loader2 className="h-8 w-8 animate-spin text-primary" />
                  <p className="text-sm text-muted-foreground">Reading the image and pulling tendencies...</p>
                </div>
              ) : null}

              {streamingContent ? (
                <div className="space-y-4">
                  <MarkdownContent content={streamingContent} />

                  {!isStreaming && traceUrlTemplate && currentTraceId && (
                    <div className="border-t pt-6">
                      <div className="flex items-center justify-between mb-2">
                        <h4 className="font-medium">See trace in MLflow UI</h4>
                        <Button
                          variant="default"
                          size="sm"
                          className="bg-blue-600 hover:bg-blue-700"
                          onClick={() =>
                            window.open(`${traceUrlTemplate}${currentTraceId}`, "_blank")
                          }
                        >
                          <ExternalLink className="h-4 w-4 mr-2" />
                          View Trace
                        </Button>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        Note: the image isn't shown on the trace's Summary tab -- click into{" "}
                        <strong>Details &amp; Timeline → Completions</strong> to see it in the
                        Chat view.
                      </p>
                    </div>
                  )}
                </div>
              ) : null}

              {!isStreaming && !streamingContent ? (
                <div className="text-center py-12 text-muted-foreground">
                  <ImageIcon className="h-8 w-8 mx-auto mb-3 opacity-40" />
                  <p>Click a formation above (or upload your own) to see the agent in action</p>
                  <p className="text-xs mt-2">The image is part of the trace, alongside the tool calls and text</p>
                </div>
              ) : null}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
